language: c # or other C/C++ variants

sudo: false

# https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - nim

os:
  - linux
  - osx

install:
  # build nim from our own branch, to avoid downtime due to nim regressions
  - "export NIMVER=$(git ls-remote https://github.com/status-im/nim.git HEAD | cut -f 1)"
  - "{ [ -f nim/$NIMVER/bin/nim ] && [ -f nim/$NIMVER/bin/nimble ] ; } || { rm -rf nim ; mkdir -p nim; git clone https://github.com/status-im/nim.git nim/$NIMVER; cd nim/$NIMVER; sh build_all.sh; cd ../.. ; }"
  - "export PATH=$PWD/nim/$NIMVER/bin:$PATH"

script:
  - nimble install -dy && nimble test
